version: 2.1

jobs:
  main:
    machine: true
    steps:
      - checkout  
      - run:
          name: "Start containers"
          command: sudo ./script.sh
      - run:
          name: "Check containers"
          command: ./.circleci/check_containers.sh
      - run:
          name: "Run spring tests"
          command: ./.circleci/run_spring_tests.sh
      - store_artifacts:
          path: /tmp/test-logs/containers
          destination: test-logs/containers
      - store_artifacts:
          path: /tmp/test-logs/spring-tests
          destination: test-logs/spring-tests
      # - store_test_results:
      #     path: /tmp/test-results

workflows:
  main-workflow:
    jobs:
      - main
