version: 2.1

jobs:
  main:
    machine: true
    steps:
      - checkout  
      - run:
          name: "Start containers"
          command: sudo ./script.sh
      - run:
          name: "Check containers"
          command: sudo ./.circleci/check_containers.sh
      - store_artifacts:
          path: /tmp/test-logs
          destination: test-logs
      # - store_test_results:
      #     path: /tmp/test-results

workflows:
  main-workflow:
    jobs:
      - main
