version: 2.1

jobs:
  build:
    machine: true
    resource_class: medium
    steps:
      - checkout  
      - run:
          name: "Start containers"
          command: sudo ./script.sh
      - run:
          name: "Check containers"
          command: ./.circleci/check_containers.sh
      - store_artifacts:
          path: /tmp/test-logs/
          destination: test-logs/

  test-spring:
    machine: true
    resource_class: medium
    steps:
      - checkout  
      - run:
          name: "Start containers"
          command: sudo ./script.sh
      - run:
          name: "Run spring tests"
          command: ./.circleci/run_spring_tests.sh
      - store_artifacts:
          path: /tmp/test-logs/
          destination: test-logs/
      - store_test_results:
          path: ./project/test-results/
          destination: test-results/
  
  deploy:
    machine: true
    resource_class: medium
    steps:
      - checkout  
      - run:
          name: "Deploy"
          command: echo "Deploying..."


workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test-spring:
          requires:
            - build
      - deploy-approval:
          type: approval
          requires:
            - test-spring
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - deploy-approval
          filters:
            branches:
              only:
                - main
