version: 2.1

jobs:
  build:
    machine: true
    resource_class: medium
    steps:
      - checkout  
      - run:
          name: "Start containers"
          command: sudo ./script.sh
      - run:
          name: "Check containers"
          command: ./.circleci/check_containers.sh
  test:
    machine: true
    resource_class: medium
    steps:
      - checkout  
      - run:
          name: "Run spring tests"
          command: ./.circleci/run_spring_tests.sh
      - store_artifacts:
          path: /tmp/test-logs/
          destination: test-logs/
      - store_test_results:
          path: ./project/test-results/
          destination: test-results/

workflows:
  main-workflow:
    jobs:
      - build
      - test
