# logging level
logging:
  level:
    org.springframework: ERROR
    com.project: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file:
    name: spring-app.log

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: SjmBZlRTi74oSMRkF1NOv1nCxX0Ze5Uc
            client-secret: ZNKbjZbk8edwy5ibpxddVq222AAFMyyRN02glQ5Qob9wWl2qukxkcodRk-vBFmWQ
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://adelin.eu.auth0.com/
  mail:
    host: smtp.gmail.com
    port: 587
    username: ukrainianrefugees123@gmail.com
    password: fvpvdrfkicykdcdc
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

server:
  ssl:
    key-store: classpath:springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password
  port: 8443
